import nextVitals from 'eslint-config-next/core-web-vitals'

const config = [
  ...nextVitals,
  {
    ignores: [
      '.next/**',
      '**/.next/**',
      'node_modules/**',
      'out/**',
      'output/**',
      'grow-os-prod/**',
      'public/locked-assets/**',
      'test-results/**',
      'tmp-logo-pack/**',
      'mobile-shell/**',
      '.adal/**',
      '.aider-desk/**',
      '.augment/**',
      '.bob/**',
      '.claude/**',
      '.codeartsdoer/**',
      '.codebuddy/**',
      '.codemaker/**',
      '.codestudio/**',
      '.commandcode/**',
      '.continue/**',
      '.cortex/**',
      '.crush/**',
      '.devin/**',
      '.factory/**',
      '.forge/**',
      '.goose/**',
      '.hermes/**',
      '.iflow/**',
      '.junie/**',
      '.kilocode/**',
      '.kiro/**',
      '.kode/**',
      '.mcpjam/**',
      '.mux/**',
      '.neovate/**',
      '.openhands/**',
      '.pi/**',
      '.pochi/**',
      '.qoder/**',
      '.qwen/**',
      '.roo/**',
      '.rovodev/**',
      '.tabnine/**',
      '.trae/**',
      '.vibe/**',
      '.vscode/**',
      '.windsurf/**',
      '.zencoder/**',
      'skills/**',
    ],
  },
]

export default config
